In [2]:
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .master("local[*]") \
    .appName("blue-owls-assessment") \
    .getOrCreate()

spark.version

'3.5.0'

In [3]:
import os
import requests
import pandas as pd
from datetime import datetime

API_BASE_URL = os.environ.get("API_BASE_URL", "http://mock-api:8000")
API_USERNAME = os.environ.get("API_USERNAME", "candidate")
API_PASSWORD = os.environ.get("API_PASSWORD", "blue-owls-2026")

print(API_BASE_URL)
print(API_USERNAME)

http://mock-api:8000
candidate

In [4]:
auth_response = requests.post(
    f"{API_BASE_URL}/api/v1/auth/token",
    json={
        "username": API_USERNAME,
        "password": API_PASSWORD
    }
)

print("Status code:", auth_response.status_code)
print(auth_response.json())

Status code: 200
{'access_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYW5kaWRhdGUiLCJpYXQiOjE3NzQ1NTQ0NjEsImV4cCI6MTc3NDU1NTM2MX0.gVcCrkeWkTSjG2ey7he7f7bG4ECozObkZ8aIIBcBuEU', 'token_type': 'bearer', 'expires_in': 900}

In [5]:
token = auth_response.json()["access_token"]

headers = {
    "Authorization": f"Bearer {token}"
}

print("Token set successfully")

Token set successfully

In [6]:
response = requests.get(
    f"{API_BASE_URL}/api/v1/data/orders",
    headers=headers,
    params={
        "page": 1,
        "page_size": 5
    }
)

print(response.status_code)
data = response.json()
print(data.keys())
print(data["data"][:2])

200
dict_keys(['data', 'pagination'])
[{'order_id': 'e481f51cbdc54678b7cc49136f2d6af7', 'customer_id': '9ef432eb6251297304e76186b10a928d', 'order_status': 'delivered', 'order_purchase_timestamp': '2017-10-02 10:56:33', 'order_approved_at': '2017-10-02 11:07:15', 'order_delivered_carrier_date': '2017-10-04 19:55:00', 'order_delivered_customer_date': '2017-10-10 21:25:13', 'order_estimated_delivery_date': '2017-10-18 00:00:00'}, {'order_id': '53cdb2fc8bc7dce0b6741e2150273451', 'customer_id': 'b0830fb4747a6c6d20dea0b8c802d7ef', 'order_status': 'delivered', 'order_purchase_timestamp': '2018-07-24 20:41:37', 'order_approved_at': '2018-07-26 03:24:27', 'order_delivered_carrier_date': '2018-07-26 14:31:00', 'order_delivered_customer_date': '2018-08-07 15:27:45', 'order_estimated_delivery_date': '2018-08-13 00:00:00'}]

In [7]:
orders_df = pd.DataFrame(data["data"])

print("Rows:", len(orders_df))
print("Columns:", list(orders_df.columns))
orders_df.head(2)

Rows: 5
Columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00

In [8]:
orders_df["_ingested_at"] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
orders_df["_source_endpoint"] = "orders"

orders_df.head(2)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,_ingested_at,_source_endpoint
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2026-03-26 19:50:46,orders
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2026-03-26 19:50:46,orders

In [9]:
orders_df.to_csv("/home/jovyan/work/output/bronze/orders_page1.csv", index=False)

print("Saved successfully")

OSError: Cannot save file into a non-existent directory: '/home/jovyan/work/output/bronze'

In [10]:
import os

os.makedirs("/home/jovyan/work/output/bronze", exist_ok=True)

print("Folder created")

Folder created

In [11]:
orders_df.to_csv("/home/jovyan/work/output/bronze/orders_page1.csv", index=False)

print("Saved successfully")

Saved successfully

In [12]:
response_page2 = requests.get(
    f"{API_BASE_URL}/api/v1/data/orders",
    headers=headers,
    params={
        "page": 2,
        "page_size": 5
    }
)

print(response_page2.status_code)

page2_data = response_page2.json()
print(page2_data["pagination"])

orders_page2_df = pd.DataFrame(page2_data["data"])
orders_page2_df["_ingested_at"] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
orders_page2_df["_source_endpoint"] = "orders"

orders_page2_df.head(2)

500

KeyError: 'pagination'

In [13]:
print(response_page2.status_code)
print(response_page2.text)

500
{"detail":"Internal server error. Please retry."}

In [14]:
if response_page2.status_code == 200:
    page2_data = response_page2.json()
    
    if "data" in page2_data:
        orders_page2_df = pd.DataFrame(page2_data["data"])
        
        orders_page2_df["_ingested_at"] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        orders_page2_df["_source_endpoint"] = "orders"
        
        print("Page 2 loaded")
        display(orders_page2_df.head(2))
    else:
        print("Data key missing in response")
else:
    print("API failed with status:", response_page2.status_code)

API failed with status: 500

In [16]:
import time

def get_orders_page_with_retry(page, page_size=5, max_retries=5):
    for attempt in range(1, max_retries + 1):
        response = requests.get(
            f"{API_BASE_URL}/api/v1/data/orders",
            headers=headers,
            params={
                "page": page,
                "page_size": page_size
            }
        )
        
        if response.status_code == 200:
            print(f"Success on attempt {attempt}")
            return response
        
        elif response.status_code in [500, 429]:
            print(f"Attempt {attempt} failed with {response.status_code}. Retrying...")
            time.sleep(2)
        
        else:
            print(f"Failed with status code: {response.status_code}")
            print(response.text)
            return response
    
    print("Max retries reached")
    return None

In [17]:
response_page2 = get_orders_page_with_retry(page=2, page_size=5)

Success on attempt 1

In [18]:
page2_data = response_page2.json()

print(page2_data.keys())
print(page2_data["pagination"])

orders_page2_df = pd.DataFrame(page2_data["data"])
orders_page2_df["_ingested_at"] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
orders_page2_df["_source_endpoint"] = "orders"

orders_page2_df.head(2)

dict_keys(['data', 'pagination'])
{'page': 2, 'page_size': 5, 'total_records': 99441, 'total_pages': 19889, 'has_next': True}

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,_ingested_at,_source_endpoint
0,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00,2026-03-26 19:58:39,orders
1,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,,,2017-05-09 00:00:00,2026-03-26 19:58:39,orders

In [19]:
def fetch_orders_pages(start_page=1, end_page=3, page_size=5):
    all_dataframes = []
    
    for page in range(start_page, end_page + 1):
        response = get_orders_page_with_retry(page=page, page_size=page_size)
        
        if response is None:
            print(f"Skipping page {page} after max retries")
            continue
        
        page_data = response.json()
        
        if "data" not in page_data:
            print(f"Skipping page {page} because 'data' key is missing")
            continue
        
        page_df = pd.DataFrame(page_data["data"])
        page_df["_ingested_at"] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        page_df["_source_endpoint"] = "orders"
        page_df["_page_number"] = page
        
        all_dataframes.append(page_df)
        print(f"Page {page} loaded with {len(page_df)} rows")
    
    if all_dataframes:
        final_df = pd.concat(all_dataframes, ignore_index=True)
        return final_df
    else:
        return pd.DataFrame()

In [20]:
orders_test_df = fetch_orders_pages(start_page=1, end_page=3, page_size=5)

print("Total rows:", len(orders_test_df))
orders_test_df.head(10)

Success on attempt 1
Page 1 loaded with 5 rows
Success on attempt 1
Page 2 loaded with 5 rows
Success on attempt 1
Page 3 loaded with 5 rows
Total rows: 15

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,_ingested_at,_source_endpoint,_page_number
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2026-03-26 20:00:17,orders,1
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2026-03-26 20:00:17,orders,1
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2026-03-26 20:00:17,orders,1
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,2026-03-26 20:00:17,orders,1
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,2026-03-26 20:00:17,orders,1
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00,2026-03-26 20:00:17,orders,2
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,,,2017-05-09 00:00:00,2026-03-26 20:00:17,orders,2
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00,2026-03-26 20:00:17,orders,2
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00,2026-03-26 20:00:17,orders,2
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00,2026-03-26 20:00:17,orders,2

In [21]:
orders_test_df.to_csv("/home/jovyan/work/output/bronze/orders_test_pages.csv", index=False)

print("orders_test_pages.csv saved successfully")

orders_test_pages.csv saved successfully

In [22]:
def fetch_all_orders(page_size=1000):
    all_dataframes = []
    page = 1
    
    while True:
        response = get_orders_page_with_retry(page=page, page_size=page_size)
        
        if response is None:
            print(f"Stopping at page {page}")
            break
        
        data = response.json()
        
        if "data" not in data or len(data["data"]) == 0:
            print(f"No more data at page {page}")
            break
        
        df = pd.DataFrame(data["data"])
        df["_ingested_at"] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        df["_source_endpoint"] = "orders"
        df["_page_number"] = page
        
        all_dataframes.append(df)
        
        print(f"Page {page} done ({len(df)} rows)")
        
        page += 1
    
    final_df = pd.concat(all_dataframes, ignore_index=True)
    return final_df

In [23]:
orders_full_df = fetch_all_orders(page_size=1000)

print("Total rows:", len(orders_full_df))

Failed with status code: 401
{"detail":"Token has expired. Please re-authenticate at /api/v1/auth/token"}
No more data at page 1

ValueError: No objects to concatenate

In [24]:
def fetch_all_orders(page_size=1000, max_pages=5):
    all_dataframes = []
    page = 1
    
    while page <= max_pages:
        response = get_orders_page_with_retry(page=page, page_size=page_size)
        
        if response is None:
            print(f"Stopping at page {page} because response is None")
            break
        
        try:
            data = response.json()
        except Exception as e:
            print(f"JSON parse failed on page {page}: {e}")
            break
        
        if "data" not in data:
            print(f"'data' key missing on page {page}")
            print(data)
            break
        
        if len(data["data"]) == 0:
            print(f"No more data at page {page}")
            break
        
        df = pd.DataFrame(data["data"])
        
        if df.empty:
            print(f"Empty dataframe on page {page}")
            break
        
        df["_ingested_at"] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        df["_source_endpoint"] = "orders"
        df["_page_number"] = page
        
        all_dataframes.append(df)
        print(f"Page {page} done ({len(df)} rows)")
        
        page += 1
    
    if len(all_dataframes) == 0:
        print("No pages were loaded.")
        return pd.DataFrame()
    
    final_df = pd.concat(all_dataframes, ignore_index=True)
    return final_df

In [25]:
orders_full_df = fetch_all_orders(page_size=1000, max_pages=5)

print("Total rows:", len(orders_full_df))
orders_full_df.head(2)

Failed with status code: 401
{"detail":"Token has expired. Please re-authenticate at /api/v1/auth/token"}
'data' key missing on page 1
{'detail': 'Token has expired. Please re-authenticate at /api/v1/auth/token'}
No pages were loaded.
Total rows: 0

Empty DataFrame
Columns: []
Index: []

In [26]:
def get_access_token():
    auth_response = requests.post(
        f"{API_BASE_URL}/api/v1/auth/token",
        json={
            "username": API_USERNAME,
            "password": API_PASSWORD
        }
    )
    
    auth_response.raise_for_status()
    token = auth_response.json()["access_token"]
    return token

token = get_access_token()

headers = {
    "Authorization": f"Bearer {token}"
}

print("New token generated successfully")

New token generated successfully

In [27]:
def get_orders_page_with_retry(page, page_size=5, max_retries=5):
    global headers
    
    for attempt in range(1, max_retries + 1):
        response = requests.get(
            f"{API_BASE_URL}/api/v1/data/orders",
            headers=headers,
            params={
                "page": page,
                "page_size": page_size
            }
        )
        
        if response.status_code == 200:
            print(f"Success on attempt {attempt}")
            return response
        
        elif response.status_code == 401:
            print(f"Attempt {attempt} got 401. Refreshing token...")
            new_token = get_access_token()
            headers = {
                "Authorization": f"Bearer {new_token}"
            }
            time.sleep(1)
        
        elif response.status_code in [500, 429]:
            print(f"Attempt {attempt} failed with {response.status_code}. Retrying...")
            time.sleep(2)
        
        else:
            print(f"Failed with status code: {response.status_code}")
            print(response.text)
            return response
    
    print("Max retries reached")
    return None

In [28]:
test_response = get_orders_page_with_retry(page=1, page_size=5)
print(test_response.status_code if test_response else "No response")

Attempt 1 failed with 500. Retrying...
Success on attempt 2
200

In [29]:
orders_full_df = fetch_all_orders(page_size=1000, max_pages=5)

print("Total rows:", len(orders_full_df))
orders_full_df.head(2)

Attempt 1 failed with 500. Retrying...
Attempt 2 failed with 429. Retrying...
Success on attempt 3
Page 1 done (1000 rows)
Success on attempt 1
Page 2 done (1000 rows)
Success on attempt 1
Page 3 done (1000 rows)
Attempt 1 failed with 500. Retrying...
Success on attempt 2
Page 4 done (1000 rows)
Attempt 1 failed with 500. Retrying...
Success on attempt 2
Page 5 done (1000 rows)
Total rows: 5000

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,_ingested_at,_source_endpoint,_page_number
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2026-03-26 20:10:15,orders,1
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2026-03-26 20:10:15,orders,1

In [30]:
orders_full_df.to_csv("/home/jovyan/work/output/bronze/orders_5pages.csv", index=False)

print("orders_5pages.csv saved successfully")

orders_5pages.csv saved successfully

In [31]:
first_page_response = get_orders_page_with_retry(page=1, page_size=1000)

first_page_json = first_page_response.json()

print(first_page_json["pagination"])

Success on attempt 1
{'page': 1, 'page_size': 1000, 'total_records': 99441, 'total_pages': 100, 'has_next': True}

In [32]:
orders_full_df = fetch_all_orders(page_size=1000, max_pages=100)

print("Total rows fetched:", len(orders_full_df))
orders_full_df.head(2)

Success on attempt 1
Page 1 done (1000 rows)
Attempt 1 failed with 429. Retrying...
Success on attempt 2
Page 2 done (1000 rows)
Success on attempt 1
Page 3 done (1000 rows)
Attempt 1 failed with 500. Retrying...
Success on attempt 2
Page 4 done (1000 rows)
Success on attempt 1
Page 5 done (1000 rows)
Success on attempt 1
Page 6 done (1000 rows)
Success on attempt 1
Page 7 done (1000 rows)
Success on attempt 1
Page 8 done (1000 rows)
Success on attempt 1
Page 9 done (1000 rows)
Attempt 1 failed with 429. Retrying...
Success on attempt 2
Page 10 done (1000 rows)
Success on attempt 1
Page 11 done (1000 rows)
Success on attempt 1
Page 12 done (1000 rows)
Success on attempt 1
Page 13 done (1000 rows)
Success on attempt 1
Page 14 done (1000 rows)
Success on attempt 1
Page 15 done (1000 rows)
Success on attempt 1
Page 16 done (1000 rows)
Success on attempt 1
Page 17 done (1000 rows)
Success on attempt 1
Page 18 done (1000 rows)
Attempt 1 failed with 429. Retrying...
Success on attempt 2
Page 19 done (1000 rows)
Success on attempt 1
Page 20 done (1000 rows)
Success on attempt 1
Page 21 done (1000 rows)
Success on attempt 1
Page 22 done (1000 rows)
Success on attempt 1
Page 23 done (1000 rows)
Success on attempt 1
Page 24 done (1000 rows)
Success on attempt 1
Page 25 done (1000 rows)
Success on attempt 1
Page 26 done (1000 rows)
Success on attempt 1
Page 27 done (1000 rows)
Attempt 1 failed with 429. Retrying...
Success on attempt 2
Page 28 done (1000 rows)
Success on attempt 1
Page 29 done (1000 rows)
Success on attempt 1
Page 30 done (1000 rows)
Success on attempt 1
Page 31 done (1000 rows)
Success on attempt 1
Page 32 done (1000 rows)
Success on attempt 1
Page 33 done (1000 rows)
Success on attempt 1
Page 34 done (1000 rows)
Success on attempt 1
Page 35 done (1000 rows)
Success on attempt 1
Page 36 done (1000 rows)
Attempt 1 failed with 429. Retrying...
Attempt 2 failed with 500. Retrying...
Success on attempt 3
Page 37 done (1000 rows)
Success on attempt 1
Page 38 done (1000 rows)
Success on attempt 1
Page 39 done (1000 rows)
Success on attempt 1
Page 40 done (1000 rows)
Success on attempt 1
Page 41 done (1000 rows)
Attempt 1 failed with 500. Retrying...
Success on attempt 2
Page 42 done (1000 rows)
Success on attempt 1
Page 43 done (1000 rows)
Attempt 1 failed with 429. Retrying...
Success on attempt 2
Page 44 done (1000 rows)
Success on attempt 1
Page 45 done (1000 rows)
Attempt 1 failed with 500. Retrying...
Success on attempt 2
Page 46 done (1000 rows)
Attempt 1 failed with 500. Retrying...
Success on attempt 2
Page 47 done (1000 rows)
Success on attempt 1
Page 48 done (1000 rows)
Success on attempt 1
Page 49 done (1000 rows)
Success on attempt 1
Page 50 done (1000 rows)
Attempt 1 failed with 429. Retrying...
Success on attempt 2
Page 51 done (1000 rows)
Success on attempt 1
Page 52 done (1000 rows)
Success on attempt 1
Page 53 done (1000 rows)
Success on attempt 1
Page 54 done (1000 rows)
Success on attempt 1
Page 55 done (1000 rows)
Success on attempt 1
Page 56 done (1000 rows)
Success on attempt 1
Page 57 done (1000 rows)
Success on attempt 1
Page 58 done (1000 rows)
Success on attempt 1
Page 59 done (1000 rows)
Attempt 1 failed with 429. Retrying...
Success on attempt 2
Page 60 done (1000 rows)
Success on attempt 1
Page 61 done (1000 rows)
Attempt 1 failed with 500. Retrying...
Success on attempt 2
Page 62 done (1000 rows)
Attempt 1 failed with 500. Retrying...
Success on attempt 2
Page 63 done (1000 rows)
Success on attempt 1
Page 64 done (1000 rows)
Success on attempt 1
Page 65 done (1000 rows)
Success on attempt 1
Page 66 done (1000 rows)
Attempt 1 failed with 429. Retrying...
Success on attempt 2
Page 67 done (1000 rows)
Success on attempt 1
Page 68 done (1000 rows)
Success on attempt 1
Page 69 done (1000 rows)
Success on attempt 1
Page 70 done (1000 rows)
Success on attempt 1
Page 71 done (1000 rows)
Success on attempt 1
Page 72 done (1000 rows)
Success on attempt 1
Page 73 done (1000 rows)
Attempt 1 failed with 500. Retrying...
Success on attempt 2
Page 74 done (1000 rows)
Attempt 1 failed with 429. Retrying...
Success on attempt 2
Page 75 done (1000 rows)
Success on attempt 1
Page 76 done (1000 rows)
Success on attempt 1
Page 77 done (1000 rows)
Success on attempt 1
Page 78 done (1000 rows)
Success on attempt 1
Page 79 done (1000 rows)
Success on attempt 1
Page 80 done (1000 rows)
Success on attempt 1
Page 81 done (1000 rows)
Success on attempt 1
Page 82 done (1000 rows)
Success on attempt 1
Page 83 done (1000 rows)
Attempt 1 failed with 429. Retrying...
Success on attempt 2
Page 84 done (1000 rows)
Success on attempt 1
Page 85 done (1000 rows)
Success on attempt 1
Page 86 done (1000 rows)
Success on attempt 1
Page 87 done (1000 rows)
Success on attempt 1
Page 88 done (1000 rows)
Success on attempt 1
Page 89 done (1000 rows)
Success on attempt 1
Page 90 done (1000 rows)
Attempt 1 failed with 500. Retrying...
Success on attempt 2
Page 91 done (1000 rows)
Attempt 1 failed with 429. Retrying...
Success on attempt 2
Page 92 done (1000 rows)
Success on attempt 1
Page 93 done (1000 rows)
Success on attempt 1
Page 94 done (1000 rows)
Success on attempt 1
Page 95 done (1000 rows)
Success on attempt 1
Page 96 done (1000 rows)
Success on attempt 1
Page 97 done (1000 rows)
Success on attempt 1
Page 98 done (1000 rows)
Success on attempt 1
Page 99 done (1000 rows)
Success on attempt 1
Page 100 done (441 rows)
Total rows fetched: 99441

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,_ingested_at,_source_endpoint,_page_number
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2026-03-26 20:13:53,orders,1
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2026-03-26 20:13:53,orders,1

In [33]:
orders_full_df.to_csv("/home/jovyan/work/output/bronze/orders.csv", index=False)

print("FULL orders.csv saved successfully")

FULL orders.csv saved successfully

In [34]:
def fetch_all_data(endpoint, page_size=1000, max_pages=100):
    all_dataframes = []
    page = 1
    
    while page <= max_pages:
        response = requests.get(
            f"{API_BASE_URL}/api/v1/data/{endpoint}",
            headers=headers,
            params={
                "page": page,
                "page_size": page_size
            }
        )
        
        # Retry logic
        if response.status_code in [500, 429]:
            print(f"{endpoint} - page {page} retrying...")
            time.sleep(2)
            continue
        
        if response.status_code == 401:
            print("Token expired, refreshing...")
            new_token = get_access_token()
            global headers
            headers = {"Authorization": f"Bearer {new_token}"}
            continue
        
        if response.status_code != 200:
            print(f"Failed {endpoint} page {page}")
            break
        
        data = response.json()
        
        if "data" not in data or len(data["data"]) == 0:
            print(f"{endpoint} completed at page {page}")
            break
        
        df = pd.DataFrame(data["data"])
        df["_ingested_at"] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        df["_source_endpoint"] = endpoint
        df["_page_number"] = page
        
        all_dataframes.append(df)
        
        print(f"{endpoint} page {page} done ({len(df)} rows)")
        
        page += 1
    
    final_df = pd.concat(all_dataframes, ignore_index=True)
    return final_df

SyntaxError: name 'headers' is used prior to global declaration (3439961911.py, line 24)

In [35]:
def fetch_all_data(endpoint, page_size=1000, max_pages=100):
    global headers  # 👈 yaha hona chahiye (top pe)

    all_dataframes = []
    page = 1
    
    while page <= max_pages:
        response = requests.get(
            f"{API_BASE_URL}/api/v1/data/{endpoint}",
            headers=headers,
            params={
                "page": page,
                "page_size": page_size
            }
        )
        
        # Retry logic
        if response.status_code in [500, 429]:
            print(f"{endpoint} - page {page} retrying...")
            time.sleep(2)
            continue
        
        if response.status_code == 401:
            print("Token expired, refreshing...")
            new_token = get_access_token()
            headers = {"Authorization": f"Bearer {new_token}"}
            continue
        
        if response.status_code != 200:
            print(f"Failed {endpoint} page {page}")
            break
        
        data = response.json()
        
        if "data" not in data or len(data["data"]) == 0:
            print(f"{endpoint} completed at page {page}")
            break
        
        df = pd.DataFrame(data["data"])
        df["_ingested_at"] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
        df["_source_endpoint"] = endpoint
        df["_page_number"] = page
        
        all_dataframes.append(df)
        
        print(f"{endpoint} page {page} done ({len(df)} rows)")
        
        page += 1
    
    final_df = pd.concat(all_dataframes, ignore_index=True)
    return final_df

In [36]:
customers_df = fetch_all_data("customers", page_size=1000, max_pages=50)

customers - page 1 retrying...
customers page 1 done (1000 rows)
customers page 2 done (1000 rows)
customers page 3 done (1000 rows)
customers page 4 done (1000 rows)
customers page 5 done (1000 rows)
customers - page 6 retrying...
customers page 6 done (1000 rows)
customers page 7 done (1000 rows)
customers - page 8 retrying...
customers - page 8 retrying...
customers page 8 done (1000 rows)
customers page 9 done (1000 rows)
customers page 10 done (1000 rows)
customers page 11 done (1000 rows)
customers page 12 done (1000 rows)
customers page 13 done (1000 rows)
customers page 14 done (1000 rows)
customers page 15 done (1000 rows)
customers page 16 done (1000 rows)
customers - page 17 retrying...
customers page 17 done (1000 rows)
customers page 18 done (1000 rows)
customers page 19 done (1000 rows)
customers page 20 done (1000 rows)
customers page 21 done (1000 rows)
customers page 22 done (1000 rows)
customers page 23 done (1000 rows)
customers page 24 done (1000 rows)
customers page 25 done (1000 rows)
customers - page 26 retrying...
customers - page 26 retrying...
customers page 26 done (1000 rows)
customers page 27 done (1000 rows)
customers page 28 done (1000 rows)
customers page 29 done (1000 rows)
customers - page 30 retrying...
customers page 30 done (1000 rows)
customers page 31 done (1000 rows)
customers page 32 done (1000 rows)
customers - page 33 retrying...
customers - page 33 retrying...
customers page 33 done (1000 rows)
customers page 34 done (1000 rows)
customers page 35 done (1000 rows)
customers page 36 done (1000 rows)
customers page 37 done (1000 rows)
customers page 38 done (1000 rows)
customers page 39 done (1000 rows)
customers page 40 done (1000 rows)
customers - page 41 retrying...
customers page 41 done (1000 rows)
customers page 42 done (1000 rows)
customers page 43 done (1000 rows)
customers page 44 done (1000 rows)
customers page 45 done (1000 rows)
customers page 46 done (1000 rows)
customers page 47 done (1000 rows)
customers page 48 done (1000 rows)
customers page 49 done (1000 rows)
customers - page 50 retrying...
customers page 50 done (1000 rows)

In [37]:
resp = requests.get(
    f"{API_BASE_URL}/api/v1/data/customers",
    headers=headers,
    params={"page": 1, "page_size": 1000}
)

print(resp.status_code)
print(resp.json()["pagination"])

200
{'page': 1, 'page_size': 1000, 'total_records': 99441, 'total_pages': 100, 'has_next': True}

In [38]:
customers_full_df = fetch_all_data("customers", page_size=1000, max_pages=100)

print("Customers total rows:", len(customers_full_df))
customers_full_df.head(2)

customers page 1 done (1000 rows)
customers page 2 done (1000 rows)
customers page 3 done (1000 rows)
customers page 4 done (1000 rows)
customers page 5 done (1000 rows)
customers page 6 done (1000 rows)
customers page 7 done (1000 rows)
customers - page 8 retrying...
customers page 8 done (1000 rows)
customers page 9 done (1000 rows)
customers page 10 done (1000 rows)
customers page 11 done (1000 rows)
customers - page 12 retrying...
customers page 12 done (1000 rows)
customers page 13 done (1000 rows)
customers page 14 done (1000 rows)
customers page 15 done (1000 rows)
customers - page 16 retrying...
customers page 16 done (1000 rows)
customers page 17 done (1000 rows)
customers page 18 done (1000 rows)
customers page 19 done (1000 rows)
customers - page 20 retrying...
customers page 20 done (1000 rows)
customers page 21 done (1000 rows)
customers - page 22 retrying...
customers page 22 done (1000 rows)
customers - page 23 retrying...
customers page 23 done (1000 rows)
customers page 24 done (1000 rows)
customers page 25 done (1000 rows)
customers page 26 done (1000 rows)
customers - page 27 retrying...
customers - page 27 retrying...
customers page 27 done (1000 rows)
customers page 28 done (1000 rows)
customers page 29 done (1000 rows)
customers - page 30 retrying...
customers page 30 done (1000 rows)
customers - page 31 retrying...
customers page 31 done (1000 rows)
customers page 32 done (1000 rows)
customers page 33 done (1000 rows)
customers - page 34 retrying...
customers page 34 done (1000 rows)
customers page 35 done (1000 rows)
customers page 36 done (1000 rows)
customers - page 37 retrying...
customers - page 37 retrying...
customers page 37 done (1000 rows)
customers - page 38 retrying...
customers page 38 done (1000 rows)
customers page 39 done (1000 rows)
customers page 40 done (1000 rows)
customers page 41 done (1000 rows)
customers page 42 done (1000 rows)
customers - page 43 retrying...
customers - page 43 retrying...
customers page 43 done (1000 rows)
customers page 44 done (1000 rows)
customers page 45 done (1000 rows)
customers page 46 done (1000 rows)
customers page 47 done (1000 rows)
customers page 48 done (1000 rows)
customers - page 49 retrying...
customers page 49 done (1000 rows)
customers page 50 done (1000 rows)
customers - page 51 retrying...
customers page 51 done (1000 rows)
customers page 52 done (1000 rows)
customers page 53 done (1000 rows)
customers page 54 done (1000 rows)
customers page 55 done (1000 rows)
customers page 56 done (1000 rows)
customers page 57 done (1000 rows)
customers page 58 done (1000 rows)
customers page 59 done (1000 rows)
customers - page 60 retrying...
customers page 60 done (1000 rows)
customers - page 61 retrying...
customers page 61 done (1000 rows)
customers page 62 done (1000 rows)
customers page 63 done (1000 rows)
customers - page 64 retrying...
customers page 64 done (1000 rows)
customers page 65 done (1000 rows)
customers page 66 done (1000 rows)
customers - page 67 retrying...
customers page 67 done (1000 rows)
customers page 68 done (1000 rows)
customers page 69 done (1000 rows)
customers page 70 done (1000 rows)
customers page 71 done (1000 rows)
customers - page 72 retrying...
customers - page 72 retrying...
customers page 72 done (1000 rows)
customers page 73 done (1000 rows)
customers - page 74 retrying...
customers page 74 done (1000 rows)
customers - page 75 retrying...
customers page 75 done (1000 rows)
customers page 76 done (1000 rows)
customers page 77 done (1000 rows)
customers page 78 done (1000 rows)
customers page 79 done (1000 rows)
customers - page 80 retrying...
customers page 80 done (1000 rows)
customers - page 81 retrying...
customers page 81 done (1000 rows)
customers - page 82 retrying...
customers page 82 done (1000 rows)
customers page 83 done (1000 rows)
customers page 84 done (1000 rows)
customers page 85 done (1000 rows)
customers page 86 done (1000 rows)
customers page 87 done (1000 rows)
customers page 88 done (1000 rows)
customers - page 89 retrying...
customers page 89 done (1000 rows)
customers page 90 done (1000 rows)
customers page 91 done (1000 rows)
customers page 92 done (1000 rows)
customers page 93 done (1000 rows)
customers page 94 done (1000 rows)
customers page 95 done (1000 rows)
customers page 96 done (1000 rows)
customers page 97 done (1000 rows)
customers - page 98 retrying...
customers page 98 done (1000 rows)
customers page 99 done (1000 rows)
customers page 100 done (441 rows)
Customers total rows: 99441

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,_ingested_at,_source_endpoint,_page_number
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,2026-03-26 20:21:34,customers,1
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP,2026-03-26 20:21:34,customers,1

In [39]:
customers_full_df.to_csv("/home/jovyan/work/output/bronze/customers.csv", index=False)

print("customers.csv saved successfully")

customers.csv saved successfully

In [40]:
products_df = fetch_all_data("products", page_size=1000, max_pages=100)
sellers_df = fetch_all_data("sellers", page_size=1000, max_pages=100)
payments_df = fetch_all_data("payments", page_size=1000, max_pages=100)
order_items_df = fetch_all_data("order_items", page_size=1000, max_pages=100)

Token expired, refreshing...
products - page 1 retrying...
products page 1 done (1000 rows)
products page 2 done (1000 rows)
products page 3 done (1000 rows)
products page 4 done (1000 rows)
products page 5 done (1000 rows)
products - page 6 retrying...
products - page 6 retrying...
products page 6 done (1000 rows)
products page 7 done (1000 rows)
products page 8 done (1000 rows)
products page 9 done (1000 rows)
products page 10 done (1000 rows)
products page 11 done (1000 rows)
products page 12 done (1000 rows)
products - page 13 retrying...
products - page 13 retrying...
products page 13 done (1000 rows)
products page 14 done (1000 rows)
products page 15 done (1000 rows)
products page 16 done (1000 rows)
products page 17 done (1000 rows)
products page 18 done (1000 rows)
products page 19 done (1000 rows)
products page 20 done (1000 rows)
products page 21 done (1000 rows)
products - page 22 retrying...
products page 22 done (1000 rows)
products page 23 done (1000 rows)
products page 24 done (1000 rows)
products page 25 done (1000 rows)
products page 26 done (1000 rows)
products page 27 done (1000 rows)
products page 28 done (1000 rows)
products page 29 done (1000 rows)
products page 30 done (1000 rows)
products - page 31 retrying...
products page 31 done (1000 rows)
products page 32 done (1000 rows)
products page 33 done (951 rows)
products completed at page 34
sellers page 1 done (1000 rows)
sellers page 2 done (1000 rows)
sellers - page 3 retrying...
sellers page 3 done (1000 rows)
sellers page 4 done (95 rows)
sellers - page 5 retrying...
sellers - page 5 retrying...
sellers completed at page 5
payments page 1 done (1000 rows)
payments page 2 done (1000 rows)
payments page 3 done (1000 rows)
payments page 4 done (1000 rows)
payments - page 5 retrying...
payments page 5 done (1000 rows)
payments page 6 done (1000 rows)
payments - page 7 retrying...
payments page 7 done (1000 rows)
payments page 8 done (1000 rows)
payments page 9 done (1000 rows)
payments page 10 done (1000 rows)
payments page 11 done (1000 rows)
payments page 12 done (1000 rows)
payments page 13 done (1000 rows)
payments page 14 done (1000 rows)
payments page 15 done (1000 rows)
payments - page 16 retrying...
payments page 16 done (1000 rows)
payments page 17 done (1000 rows)
payments page 18 done (1000 rows)
payments page 19 done (1000 rows)
payments page 20 done (1000 rows)
payments page 21 done (1000 rows)
payments page 22 done (1000 rows)
payments page 23 done (1000 rows)
payments page 24 done (1000 rows)
payments - page 25 retrying...
payments page 25 done (1000 rows)
payments page 26 done (1000 rows)
payments page 27 done (1000 rows)
payments page 28 done (1000 rows)
payments page 29 done (1000 rows)
payments page 30 done (1000 rows)
payments page 31 done (1000 rows)
payments - page 32 retrying...
payments page 32 done (1000 rows)
payments - page 33 retrying...
payments page 33 done (1000 rows)
payments page 34 done (1000 rows)
payments page 35 done (1000 rows)
payments page 36 done (1000 rows)
payments - page 37 retrying...
payments page 37 done (1000 rows)
payments page 38 done (1000 rows)
payments - page 39 retrying...
payments page 39 done (1000 rows)
payments - page 40 retrying...
payments page 40 done (1000 rows)
payments page 41 done (1000 rows)
payments - page 42 retrying...
payments page 42 done (1000 rows)
payments - page 43 retrying...
payments page 43 done (1000 rows)
payments page 44 done (1000 rows)
payments page 45 done (1000 rows)
payments page 46 done (1000 rows)
payments - page 47 retrying...
payments page 47 done (1000 rows)
payments page 48 done (1000 rows)
payments - page 49 retrying...
payments page 49 done (1000 rows)
payments page 50 done (1000 rows)
payments page 51 done (1000 rows)
payments page 52 done (1000 rows)
payments page 53 done (1000 rows)
payments page 54 done (1000 rows)
payments - page 55 retrying...
payments page 55 done (1000 rows)
payments page 56 done (1000 rows)
payments page 57 done (1000 rows)
payments - page 58 retrying...
payments page 58 done (1000 rows)
payments page 59 done (1000 rows)
payments page 60 done (1000 rows)
payments page 61 done (1000 rows)
payments page 62 done (1000 rows)
payments - page 63 retrying...
payments - page 63 retrying...
payments page 63 done (1000 rows)
payments page 64 done (1000 rows)
payments page 65 done (1000 rows)
payments page 66 done (1000 rows)
payments page 67 done (1000 rows)
payments page 68 done (1000 rows)
payments page 69 done (1000 rows)
payments page 70 done (1000 rows)
payments - page 71 retrying...
payments page 71 done (1000 rows)
payments page 72 done (1000 rows)
payments page 73 done (1000 rows)
payments page 74 done (1000 rows)
payments - page 75 retrying...
payments page 75 done (1000 rows)
payments page 76 done (1000 rows)
payments page 77 done (1000 rows)
payments page 78 done (1000 rows)
payments - page 79 retrying...
payments page 79 done (1000 rows)
payments page 80 done (1000 rows)
payments page 81 done (1000 rows)
payments page 82 done (1000 rows)
payments page 83 done (1000 rows)
payments page 84 done (1000 rows)
payments page 85 done (1000 rows)
payments - page 86 retrying...
payments page 86 done (1000 rows)
payments - page 87 retrying...
payments page 87 done (1000 rows)
payments - page 88 retrying...
payments page 88 done (1000 rows)
payments page 89 done (1000 rows)
payments page 90 done (1000 rows)
payments page 91 done (1000 rows)
payments page 92 done (1000 rows)
payments page 93 done (1000 rows)
payments page 94 done (1000 rows)
payments - page 95 retrying...
payments page 95 done (1000 rows)
payments - page 96 retrying...
payments page 96 done (1000 rows)
payments page 97 done (1000 rows)
payments page 98 done (1000 rows)
payments page 99 done (1000 rows)
payments page 100 done (1000 rows)
order_items page 1 done (1000 rows)
order_items page 2 done (1000 rows)
order_items - page 3 retrying...
order_items page 3 done (1000 rows)
order_items page 4 done (1000 rows)
order_items page 5 done (1000 rows)
order_items - page 6 retrying...
order_items page 6 done (1000 rows)
order_items - page 7 retrying...
order_items page 7 done (1000 rows)
order_items page 8 done (1000 rows)
order_items page 9 done (1000 rows)
order_items - page 10 retrying...
order_items - page 10 retrying...
order_items page 10 done (1000 rows)
order_items page 11 done (1000 rows)
order_items page 12 done (1000 rows)
order_items - page 13 retrying...
order_items page 13 done (1000 rows)
order_items page 14 done (1000 rows)
order_items page 15 done (1000 rows)
order_items page 16 done (1000 rows)
order_items - page 17 retrying...
order_items - page 17 retrying...
order_items page 17 done (1000 rows)
order_items page 18 done (1000 rows)
order_items page 19 done (1000 rows)
order_items page 20 done (1000 rows)
order_items page 21 done (1000 rows)
order_items page 22 done (1000 rows)
order_items - page 23 retrying...
order_items page 23 done (1000 rows)
order_items - page 24 retrying...
order_items page 24 done (1000 rows)
order_items - page 25 retrying...
order_items page 25 done (1000 rows)
order_items page 26 done (1000 rows)
order_items page 27 done (1000 rows)
order_items page 28 done (1000 rows)
order_items page 29 done (1000 rows)
order_items - page 30 retrying...
order_items page 30 done (1000 rows)
order_items - page 31 retrying...
order_items page 31 done (1000 rows)
order_items - page 32 retrying...
order_items page 32 done (1000 rows)
order_items page 33 done (1000 rows)
order_items page 34 done (1000 rows)
order_items - page 35 retrying...
order_items page 35 done (1000 rows)
order_items page 36 done (1000 rows)
order_items page 37 done (1000 rows)
order_items - page 38 retrying...
order_items page 38 done (1000 rows)
order_items page 39 done (1000 rows)
order_items - page 40 retrying...
order_items page 40 done (1000 rows)
order_items page 41 done (1000 rows)
order_items page 42 done (1000 rows)
order_items page 43 done (1000 rows)
order_items page 44 done (1000 rows)
order_items page 45 done (1000 rows)
order_items - page 46 retrying...
order_items page 46 done (1000 rows)
order_items page 47 done (1000 rows)
order_items page 48 done (1000 rows)
order_items page 49 done (1000 rows)
order_items page 50 done (1000 rows)
order_items page 51 done (1000 rows)
order_items page 52 done (1000 rows)
order_items - page 53 retrying...
order_items page 53 done (1000 rows)
order_items - page 54 retrying...
order_items page 54 done (1000 rows)
order_items page 55 done (1000 rows)
order_items page 56 done (1000 rows)
order_items page 57 done (1000 rows)
order_items page 58 done (1000 rows)
order_items page 59 done (1000 rows)
order_items - page 60 retrying...
order_items page 60 done (1000 rows)
order_items page 61 done (1000 rows)
order_items - page 62 retrying...
order_items page 62 done (1000 rows)
order_items page 63 done (1000 rows)
order_items page 64 done (1000 rows)
order_items - page 65 retrying...
order_items page 65 done (1000 rows)
order_items page 66 done (1000 rows)
order_items page 67 done (1000 rows)
order_items page 68 done (1000 rows)
order_items page 69 done (1000 rows)
order_items - page 70 retrying...
order_items page 70 done (1000 rows)
order_items page 71 done (1000 rows)
order_items page 72 done (1000 rows)
order_items page 73 done (1000 rows)
order_items page 74 done (1000 rows)
order_items page 75 done (1000 rows)
order_items page 76 done (1000 rows)
order_items page 77 done (1000 rows)
order_items page 78 done (1000 rows)
order_items - page 79 retrying...
order_items page 79 done (1000 rows)
order_items page 80 done (1000 rows)
order_items page 81 done (1000 rows)
order_items - page 82 retrying...
order_items page 82 done (1000 rows)
order_items page 83 done (1000 rows)
order_items - page 84 retrying...
order_items page 84 done (1000 rows)
order_items page 85 done (1000 rows)
order_items - page 86 retrying...
order_items page 86 done (1000 rows)
order_items page 87 done (1000 rows)
order_items page 88 done (1000 rows)
order_items page 89 done (1000 rows)
order_items page 90 done (1000 rows)
order_items page 91 done (1000 rows)
order_items - page 92 retrying...
order_items page 92 done (1000 rows)
order_items page 93 done (1000 rows)
order_items - page 94 retrying...
order_items page 94 done (1000 rows)
order_items page 95 done (1000 rows)
order_items page 96 done (1000 rows)
order_items page 97 done (1000 rows)
order_items page 98 done (1000 rows)
order_items page 99 done (1000 rows)
order_items page 100 done (1000 rows)

In [41]:
products_df = fetch_all_data("products", page_size=1000, max_pages=50)

products - page 1 retrying...
products page 1 done (1000 rows)
products - page 2 retrying...
products page 2 done (1000 rows)
products page 3 done (1000 rows)
products page 4 done (1000 rows)
products page 5 done (1000 rows)
products page 6 done (1000 rows)
products page 7 done (1000 rows)
products - page 8 retrying...
products page 8 done (1000 rows)
products page 9 done (1000 rows)
products - page 10 retrying...
products - page 10 retrying...
products page 10 done (1000 rows)
products page 11 done (1000 rows)
products page 12 done (1000 rows)
products page 13 done (1000 rows)
products page 14 done (1000 rows)
products page 15 done (1000 rows)
products page 16 done (1000 rows)
products page 17 done (1000 rows)
products - page 18 retrying...
products page 18 done (1000 rows)
products page 19 done (1000 rows)
products page 20 done (1000 rows)
products - page 21 retrying...
products - page 21 retrying...
products page 21 done (1000 rows)
products page 22 done (1000 rows)
products page 23 done (1000 rows)
products page 24 done (1000 rows)
products - page 25 retrying...
products page 25 done (1000 rows)
products page 26 done (1000 rows)
products page 27 done (1000 rows)
products page 28 done (1000 rows)
products page 29 done (1000 rows)
products page 30 done (1000 rows)
products page 31 done (1000 rows)
products page 32 done (1000 rows)
products page 33 done (951 rows)
products - page 34 retrying...
products completed at page 34

In [42]:
products_df.to_csv("/home/jovyan/work/output/bronze/products.csv", index=False)
sellers_df.to_csv("/home/jovyan/work/output/bronze/sellers.csv", index=False)
payments_df.to_csv("/home/jovyan/work/output/bronze/payments.csv", index=False)
order_items_df.to_csv("/home/jovyan/work/output/bronze/order_items.csv", index=False)

print("All bronze files saved successfully")

All bronze files saved successfully